#!/bin/bash

# A script to display a series of numbers using a while loop.

counter=1
while [[ "$counter" -le 10 ]]; do
    echo "The counter is at: $counter"
    counter=$((counter + 1))
done
echo "The count has finished."