#!/bin/bash

#just a conditional statement to check the correct answer

number=20
if [ $((number + 20)) -le 50 ];
then
   echo "The number $number checked is correct";
   else
      echo "The number $number checked is wrong"
   fi